[package]
version = "1.0.0"

title = "Create Extension Cutplane"
description = "Tool for adding cutplanes to create for view interiors of meshes, models, and pointclouds."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = "https://github.com/Brett-Amberge/lm-cutplane-tool"

category = "Create"

# Keywords for the extension
keywords = ["kit", "tool", "mesh"]

# Icon to show in the extension manager
icon = ""

# Preview to show in the extension manager
preview_image = ""


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides
[[python.module]]
name = "lm.cutplane.tool"

[[test]]
# Extra dependencies only to be used during test run
dependencies = [
    "omni.kit.ui_test" # UI testing extension
]
